apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline-build-multiarch
spec:
  tasks:
    - name: init
      params:
        - name: image-url
          value: $(params.output-image)

        - name: rebuild
          value: $(params.rebuild)

        - name: skip-checks
          value: $(params.skip-checks)
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: init

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-init:0.2@sha256:737682d073a65a486d59b2b30e3104b93edd8490e0cd5e9b4a39703e47363f0f

          - name: kind
            value: task

    - name: clone-repository
      params:
        - name: url
          value: $(params.git-url)

        - name: revision
          value: $(params.revision)

        - name: ociStorage
          value: $(params.output-image).git

        - name: ociArtifactExpiresAfter
          value: $(params.image-expires-after)
      runAfter:
        - init
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: git-clone-oci-ta

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta:0.1@sha256:9709088bf3c581d4763e9804d9ee3a1f06ad6a61c23237277057c4f0cdc4f9c3

          - name: kind
            value: task
      when:
        - input: $(tasks.init.results.build)
          operator: in
          values:
            - "true"
      workspaces:
        - name: basic-auth
          workspace: git-auth

    - name: prefetch-dependencies
      params:
        - name: input
          value: $(params.prefetch-input)

        - name: SOURCE_ARTIFACT
          value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)

        - name: ociStorage
          value: $(params.output-image).prefetch

        - name: ociArtifactExpiresAfter
          value: $(params.image-expires-after)
      runAfter:
        - clone-repository
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: prefetch-dependencies-oci-ta

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-prefetch-dependencies-oci-ta:0.2@sha256:efc8aebec295bf5986597b6bbeebe093b2764fea79c66094e05ff3d283f54932

          - name: kind
            value: task
      workspaces:
        - name: git-basic-auth
          workspace: git-auth

        - name: netrc
          workspace: netrc

    - name: get-version
      params:
        - name: source_artifact
          value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
      taskRef:
        name: get-version

    - name: build-image
      displayName: "build-image-$(params.PLATFORM)"
      matrix:
        params:
          - name: PLATFORM
            value:
              - $(params.build-platforms)
      params:
        - name: IMAGE
          value: $(params.output-image)

        - name: DOCKERFILE
          value: $(params.dockerfile)

        - name: CONTEXT
          value: $(params.path-context)

        - name: HERMETIC
          value: $(params.hermetic)

        - name: PREFETCH_INPUT
          value: $(params.prefetch-input)

        - name: IMAGE_EXPIRES_AFTER
          value: $(params.image-expires-after)

        - name: COMMIT_SHA
          value: $(tasks.clone-repository.results.commit)

        - name: BUILD_ARGS
          value:
            - $(params.build-args[*])
            - VERSION=$(tasks.get-version.results.version)

        - name: BUILD_ARGS_FILE
          value: $(params.build-args-file)

        - name: SOURCE_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)

        - name: CACHI2_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)

        - name: IMAGE_APPEND_PLATFORM
          value: "true"
      runAfter:
        - prefetch-dependencies
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: buildah-remote-oci-ta

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-buildah-remote-oci-ta:0.4@sha256:468708e0a5dc3a314d71ca0cf2db80c6d7fefae98b292b10fa1cf07ea3787d9e

          - name: kind
            value: task
      when:
        - input: $(tasks.init.results.build)
          operator: in
          values:
            - "true"

    - name: build-image-manifest
      params:
        - name: IMAGE
          value: $(params.output-image)

        - name: COMMIT_SHA
          value: $(tasks.clone-repository.results.commit)

        - name: IMAGE_EXPIRES_AFTER
          value: $(params.image-expires-after)

        - name: ALWAYS_BUILD_INDEX
          value: $(params.build-image-manifest)

        - name: IMAGES
          value:
            - $(tasks.build-image.results.IMAGE_REF[*])
      runAfter:
        - build-image
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: build-image-index

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-build-image-index:0.1@sha256:95be274b6d0432d4671e2c41294ec345121bdf01284b1c6c46b5537dc6b37e15

          - name: kind
            value: task
      when:
        - input: $(tasks.init.results.build)
          operator: in
          values:
            - "true"

    - name: deprecated-base-image-check
      params:
        - name: IMAGE_URL
          value: $(tasks.build-image-manifest.results.IMAGE_URL)

        - name: IMAGE_DIGEST
          value: $(tasks.build-image-manifest.results.IMAGE_DIGEST)
      runAfter:
        - build-image-manifest
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: deprecated-image-check

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-deprecated-image-check:0.5@sha256:5d63b920b71192906fe4d6c4903f594e6f34c5edcff9d21714a08b5edcfbc667

          - name: kind
            value: task
      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"

    - name: clair-scan
      params:
        - name: image-digest
          value: $(tasks.build-image-manifest.results.IMAGE_DIGEST)

        - name: image-url
          value: $(tasks.build-image-manifest.results.IMAGE_URL)
      runAfter:
        - build-image-manifest
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: clair-scan

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-clair-scan:0.2@sha256:712afcf63f3b5a97c371d37e637efbcc9e1c7ad158872339d00adc6413cd8851

          - name: kind
            value: task
      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"

    - name: ecosystem-cert-preflight-checks
      params:
        - name: image-url
          value: $(tasks.build-image-manifest.results.IMAGE_URL)
      runAfter:
        - build-image-manifest
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: ecosystem-cert-preflight-checks

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-ecosystem-cert-preflight-checks:0.2@sha256:00b13d06d17328e105b11619ee4db98b215ca6ac02314a4776aa5fc2a974f9c1

          - name: kind
            value: task
      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"

    - name: sast-snyk-check
      params:
        - name: image-digest
          value: $(tasks.build-image-manifest.results.IMAGE_DIGEST)

        - name: image-url
          value: $(tasks.build-image-manifest.results.IMAGE_URL)

        - name: SOURCE_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)

        - name: CACHI2_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
      runAfter:
        - build-image-manifest
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: sast-snyk-check-oci-ta

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-sast-snyk-check-oci-ta:0.3@sha256:a1cb59ed66a7be1949c9720660efb0a006e95ef05b3f67929dd8e310e1d7baef

          - name: kind
            value: task
      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"

    - name: clamav-scan
      params:
        - name: image-digest
          value: $(tasks.build-image-manifest.results.IMAGE_DIGEST)

        - name: image-url
          value: $(tasks.build-image-manifest.results.IMAGE_URL)
      runAfter:
        - build-image-manifest
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: clamav-scan

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-clamav-scan:0.2@sha256:62c835adae22e36fce6684460b39206bc16752f1a4427cdbba4ee9afdd279670

          - name: kind
            value: task
      when:
        - input: "{{ event_type }}"
          operator: in
          values:
            - "push"

    - name: apply-tags
      params:
        - name: IMAGE
          value: $(tasks.build-image-manifest.results.IMAGE_URL)

        - name: ADDITIONAL_TAGS
          value:
            - $(params.tag-prefix)$(tasks.clone-repository.results.short-commit)
      runAfter:
        - build-image-manifest
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: apply-tags

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-apply-tags:0.1@sha256:61c90b1c94a2a11cb11211a0d65884089b758c34254fcec164d185a402beae22

          - name: kind
            value: task

    - name: push-dockerfile
      params:
        - name: IMAGE
          value: $(tasks.build-image-manifest.results.IMAGE_URL)

        - name: IMAGE_DIGEST
          value: $(tasks.build-image-manifest.results.IMAGE_DIGEST)

        - name: DOCKERFILE
          value: $(params.dockerfile)

        - name: CONTEXT
          value: $(params.path-context)

        - name: SOURCE_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
      runAfter:
        - build-image-manifest
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: push-dockerfile-oci-ta

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-push-dockerfile-oci-ta:0.1@sha256:55a4ff2910ae2e4502f3841719935d37578bd52156bc789fcdf45ff48c2b048b

          - name: kind
            value: task

    - name: rpms-signature-scan
      params:
        - name: image-digest
          value: $(tasks.build-image-manifest.results.IMAGE_DIGEST)

        - name: image-url
          value: $(tasks.build-image-manifest.results.IMAGE_URL)
      runAfter:
        - build-image-manifest
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: rpms-signature-scan

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-rpms-signature-scan:0.2@sha256:c0798ff85ad04f1553d349fe34aa4918597fb35b3b74e344dfbd5af2f3494300

          - name: kind
            value: task

  params:
    - name: git-url
      description: Source Repository URL
      type: string

    - name: revision
      description: Revision of the Source Repository
      type: string
      default: ""

    - name: output-image
      description: Fully Qualified Output Image
      type: string

    - name: path-context
      description: Path to the source code of an application's component from where to build image.
      type: string
      default: .

    - name: dockerfile
      description: Path to the Dockerfile inside the context specified by parameter path-context
      type: string
      default: Dockerfile

    - name: rebuild
      description: Force rebuild image
      type: string
      default: "false"

    - name: skip-checks
      description: Skip checks against built image
      type: string
      default: "false"

    - name: hermetic
      description: Execute the build with network isolation
      type: string
      default: "false"

    - name: prefetch-input
      description: Build dependencies to be prefetched by Cachi2
      type: string
      default: ""

    - name: image-expires-after
      description: Image tag expiration time, time values could be something like 1h, 2d, 3w for hours, days, and weeks, respectively.
      default: ""

    - name: build-source-image
      description: Build a source image.
      type: string
      default: "false"

    - name: build-image-manifest
      description: Add built image into an OCI image index
      type: string
      default: "true"

    - name: build-args
      type: array
      description: Array of --build-arg values ("arg=value" strings) for buildah
      default: []

    - name: build-args-file
      description: Path to a file with build arguments for buildah, see https://www.mankier.com/1/buildah-build#--build-arg-file
      type: string
      default: ""

    - name: build-platforms
      description: List of platforms to build the container images on. The available set of values is determined by the configuration of the multi-platform-controller.
      type: array
      default:
        - linux/x86_64
        - linux/arm64

    - name: tag-prefix
      description: Prefix added to additional tags
      type: string
      default: ""

  workspaces:
    - name: git-auth
      optional: true

    - name: netrc
      optional: true

  results:
    - name: IMAGE_URL
      description: ""
      value: $(tasks.build-image-manifest.results.IMAGE_URL)

    - name: IMAGE_DIGEST
      description: ""
      value: $(tasks.build-image-manifest.results.IMAGE_DIGEST)

    - name: CHAINS-GIT_URL
      description: ""
      value: $(tasks.clone-repository.results.url)

    - name: CHAINS-GIT_COMMIT
      description: ""
      value: $(tasks.clone-repository.results.commit)


  finally:
    - name: show-sbom
      params:
        - name: IMAGE_URL
          value: $(tasks.build-image-manifest.results.IMAGE_URL)
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: show-sbom

          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-show-sbom:0.1@sha256:04f15cbce548e1db7770eee3f155ccb2cc0140a6c371dc67e9a34d83673ea0c0

          - name: kind
            value: task
