apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline-build-multiarch
spec:
  tasks:
    - name: init
      params:
        - name: enable-cache-proxy
          value: $(params.enable-cache-proxy)
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: init
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-init:0.3@sha256:aa6f8632cc23d605c5942505ff1d00280db16a6fda5c4c56c4ed9ae936b5fbc6
          - name: kind
            value: task
    - name: clone-repository
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.revision)
        - name: ociStorage
          value: $(params.output-image).git
        - name: ociArtifactExpiresAfter
          value: $(params.image-expires-after)
      runAfter:
        - init
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: git-clone-oci-ta
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta:0.1@sha256:306b69e6db435ad4a7cf258b6219d9b998eb37da44f5e9ac882ac86a08109154
          - name: kind
            value: task
      workspaces:
        - name: basic-auth
          workspace: git-auth
    - name: prefetch-dependencies
      params:
        - name: input
          value: $(params.prefetch-input)
        - name: SOURCE_ARTIFACT
          value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
        - name: ociStorage
          value: $(params.output-image).prefetch
        - name: ociArtifactExpiresAfter
          value: $(params.image-expires-after)
      runAfter:
        - clone-repository
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: prefetch-dependencies-oci-ta
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-prefetch-dependencies-oci-ta:0.2@sha256:c664a6df6514b59c3ce53570b0994b45af66ecc89ba2a8e41834eae0622addf6
          - name: kind
            value: task
      workspaces:
        - name: git-basic-auth
          workspace: git-auth
        - name: netrc
          workspace: netrc
    - name: get-version
      params:
        - name: source_artifact
          value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
      taskRef:
        name: get-version
    - name: build-image
      displayName: "build-image-$(params.PLATFORM)"
      matrix:
        params:
          - name: PLATFORM
            value:
              - $(params.build-platforms)
      params:
        - name: IMAGE
          value: $(params.output-image)
        - name: DOCKERFILE
          value: $(params.dockerfile)
        - name: CONTEXT
          value: $(params.path-context)
        - name: HERMETIC
          value: $(params.hermetic)
        - name: PREFETCH_INPUT
          value: $(params.prefetch-input)
        - name: IMAGE_EXPIRES_AFTER
          value: $(params.image-expires-after)
        - name: COMMIT_SHA
          value: $(tasks.clone-repository.results.commit)
        - name: BUILD_ARGS
          value:
            - $(params.build-args[*])
            - VERSION=$(tasks.get-version.results.version)
        - name: BUILD_ARGS_FILE
          value: $(params.build-args-file)
        - name: SOURCE_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
        - name: CACHI2_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
        - name: IMAGE_APPEND_PLATFORM
          value: "true"
        - name: BUILDAH_FORMAT
          value: $(params.buildah-format)
        - name: HTTP_PROXY
          value: $(tasks.init.results.http-proxy)
        - name: NO_PROXY
          value: $(tasks.init.results.no-proxy)
      runAfter:
        - prefetch-dependencies
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: buildah-remote-oci-ta
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-buildah-remote-oci-ta:0.8@sha256:4ba24114693920806b35f398fe766c167c18c77fab5f0648a0e1c0de702e4a47
          - name: kind
            value: task
    - name: build-image-manifest
      params:
        - name: IMAGE
          value: $(params.output-image)
        - name: COMMIT_SHA
          value: $(tasks.clone-repository.results.commit)
        - name: IMAGE_EXPIRES_AFTER
          value: $(params.image-expires-after)
        - name: ALWAYS_BUILD_INDEX
          value: $(params.build-image-manifest)
        - name: IMAGES
          value:
            - $(tasks.build-image.results.IMAGE_REF[*])
        - name: BUILDAH_FORMAT
          value: $(params.buildah-format)
      runAfter:
        - build-image
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: build-image-index
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-build-image-index:0.2@sha256:8c422a5380a3d877257003dee153190322af84fe6f4f25e9eee7d8bf61a62577
          - name: kind
            value: task
    - name: deprecated-base-image-check
      params:
        - name: IMAGE_URL
          value: $(tasks.build-image-manifest.results.IMAGE_URL)
        - name: IMAGE_DIGEST
          value: $(tasks.build-image-manifest.results.IMAGE_DIGEST)
      runAfter:
        - build-image-manifest
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: deprecated-image-check
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-deprecated-image-check:0.5@sha256:e3a55ccdf1091b4a35507f9ee2d1918d8e89a5f96babcb5486b491226da03d6f
          - name: kind
            value: task
      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"
    - matrix:
        params:
          - name: image-platform
            value:
              - $(params.build-platforms)
      name: clair-scan
      params:
        - name: image-digest
          value: $(tasks.build-image-manifest.results.IMAGE_DIGEST)
        - name: image-url
          value: $(tasks.build-image-manifest.results.IMAGE_URL)
      runAfter:
        - build-image-manifest
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: clair-scan
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-clair-scan:0.3@sha256:3ff4d1c3c503454c6b7f072e225df43656fb415a5d2a658ab6ce279c0dc128aa
          - name: kind
            value: task
      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"
    - name: ecosystem-cert-preflight-checks
      params:
        - name: image-url
          value: $(tasks.build-image-manifest.results.IMAGE_URL)
      runAfter:
        - build-image-manifest
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: ecosystem-cert-preflight-checks
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-ecosystem-cert-preflight-checks:0.2@sha256:33b7133c0c132c361295c30947f73bd45a3a3b62a24b83f3d8cd7c71f757828c
          - name: kind
            value: task
      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"
    - name: sast-snyk-check
      params:
        - name: image-digest
          value: $(tasks.build-image-manifest.results.IMAGE_DIGEST)
        - name: image-url
          value: $(tasks.build-image-manifest.results.IMAGE_URL)
        - name: SOURCE_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
        - name: CACHI2_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
      runAfter:
        - build-image-manifest
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: sast-snyk-check-oci-ta
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-sast-snyk-check-oci-ta:0.4@sha256:0c2ab8ce6d419400b63dd67d061052ac51de7b1ebe93f8ae86ed07ac638d756d
          - name: kind
            value: task
      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"
    - name: clamav-scan
      matrix:
        params:
          - name: image-arch
            value:
              - $(params.build-platforms)
      params:
        - name: image-digest
          value: $(tasks.build-image-manifest.results.IMAGE_DIGEST)
        - name: image-url
          value: $(tasks.build-image-manifest.results.IMAGE_URL)
      runAfter:
        - build-image-manifest
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: clamav-scan
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-clamav-scan:0.3@sha256:4f5ccf2324ecef92aaad6e2adb46c0bb15be49b4869b5b407346c514b764404f
          - name: kind
            value: task
    - name: sast-shell-check
      params:
        - name: image-digest
          value: $(tasks.build-image-manifest.results.IMAGE_DIGEST)
        - name: image-url
          value: $(tasks.build-image-manifest.results.IMAGE_URL)
        - name: SOURCE_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
        - name: CACHI2_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
      runAfter:
        - build-image-manifest
      taskRef:
        params:
          - name: name
            value: sast-shell-check-oci-ta
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-sast-shell-check-oci-ta:0.1@sha256:f475b4b6b0c1687fa1aafa5ba38813e04f080b185af2975e12b457742d9dd857
          - name: kind
            value: task
        resolver: bundles
      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"
    - name: sast-unicode-check
      params:
        - name: image-url
          value: $(tasks.build-image-manifest.results.IMAGE_URL)
        - name: image-digest
          value: $(tasks.build-image-manifest.results.IMAGE_DIGEST)
        - name: SOURCE_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
        - name: CACHI2_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
      runAfter:
        - build-image-manifest
      taskRef:
        params:
          - name: name
            value: sast-unicode-check-oci-ta
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-sast-unicode-check-oci-ta:0.4@sha256:b38140b2f0b2163def80e28a792b2702245d38a5610a504f2e56c198f3b8f70b
          - name: kind
            value: task
        resolver: bundles
      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"
    - name: apply-tags
      params:
        - name: IMAGE_URL
          value: $(tasks.build-image-manifest.results.IMAGE_URL)
        - name: IMAGE_DIGEST
          value: $(tasks.build-image-manifest.results.IMAGE_DIGEST)
        - name: ADDITIONAL_TAGS
          value:
            - $(params.tag-prefix)$(tasks.clone-repository.results.short-commit)
      runAfter:
        - build-image-manifest
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: apply-tags
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-apply-tags:0.3@sha256:510b6d2a3b188adeb716e49566b57d611ab36bd69a2794b5ddfc11dbf014c2ca
          - name: kind
            value: task
    - name: push-dockerfile
      params:
        - name: IMAGE
          value: $(tasks.build-image-manifest.results.IMAGE_URL)
        - name: IMAGE_DIGEST
          value: $(tasks.build-image-manifest.results.IMAGE_DIGEST)
        - name: DOCKERFILE
          value: $(params.dockerfile)
        - name: CONTEXT
          value: $(params.path-context)
        - name: SOURCE_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
      runAfter:
        - build-image-manifest
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: push-dockerfile-oci-ta
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-push-dockerfile-oci-ta:0.1@sha256:6fb61bec5ef161225a850005233db68cfdc03ad54e1a54cc49cc98d98ea3d259
          - name: kind
            value: task
    - name: rpms-signature-scan
      params:
        - name: image-digest
          value: $(tasks.build-image-manifest.results.IMAGE_DIGEST)
        - name: image-url
          value: $(tasks.build-image-manifest.results.IMAGE_URL)
      runAfter:
        - build-image-manifest
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: rpms-signature-scan
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-rpms-signature-scan:0.2@sha256:a99d8fd4c9027356b18e5d2910cc44dbc2fcb53c384ba34696645d9e7faa9084
          - name: kind
            value: task
  params:
    - name: git-url
      description: Source Repository URL
      type: string
    - name: revision
      description: Revision of the Source Repository
      type: string
      default: ""
    - name: output-image
      description: Fully Qualified Output Image
      type: string
    - name: path-context
      description: Path to the source code of an application's component from where to build image.
      type: string
      default: .
    - name: dockerfile
      description: Path to the Dockerfile inside the context specified by parameter path-context
      type: string
      default: Dockerfile
    - name: skip-checks
      description: Skip checks against built image
      type: string
      default: "false"
    - name: hermetic
      description: Execute the build with network isolation
      type: string
      default: "false"
    - name: prefetch-input
      description: Build dependencies to be prefetched by Cachi2
      type: string
      default: ""
    - name: image-expires-after
      description: Image tag expiration time, time values could be something like 1h, 2d, 3w for hours, days, and weeks, respectively.
      default: ""
    - name: build-source-image
      description: Build a source image.
      type: string
      default: "false"
    - name: build-image-manifest
      description: Add built image into an OCI image index
      type: string
      default: "true"
    - name: build-args
      type: array
      description: Array of --build-arg values ("arg=value" strings) for buildah
      default: []
    - name: build-args-file
      description: Path to a file with build arguments for buildah, see https://www.mankier.com/1/buildah-build#--build-arg-file
      type: string
      default: ""
    - name: build-platforms
      description: List of platforms to build the container images on. The available set of values is determined by the configuration of the multi-platform-controller.
      type: array
      default:
        - linux/x86_64
        - linux/arm64
    - name: tag-prefix
      description: Prefix added to additional tags
      type: string
      default: ""
    - name: buildah-format
      default: docker
      type: string
      description: The format for the resulting image's mediaType. Valid values are oci or docker.
    - name: enable-cache-proxy
      default: 'false'
      description: Enable cache proxy configuration
      type: string
  workspaces:
    - name: git-auth
      optional: true
    - name: netrc
      optional: true
  results:
    - name: IMAGE_URL
      description: ""
      value: $(tasks.build-image-manifest.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      description: ""
      value: $(tasks.build-image-manifest.results.IMAGE_DIGEST)
    - name: CHAINS-GIT_URL
      description: ""
      value: $(tasks.clone-repository.results.url)
    - name: CHAINS-GIT_COMMIT
      description: ""
      value: $(tasks.clone-repository.results.commit)
  finally:
    - name: show-sbom
      params:
        - name: IMAGE_URL
          value: $(tasks.build-image-manifest.results.IMAGE_URL)
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: show-sbom
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-show-sbom:0.1@sha256:e2c1b4eac642f32e91f3bc5d3cb48c5c70888aaf45c3650d9ea34573de7a7fd5
          - name: kind
            value: task
