apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/RedHatInsights/ubi-trino?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: ubi-trino
    appstudio.openshift.io/component: ubi-trino
    pipelines.appstudio.openshift.io/type: build
  name: ubi-trino-on-pull-request
  namespace: cost-mgmt-dev-tenant

spec:
  params:
    - name: git-url
      value: '{{source_url}}'

    - name: revision
      value: '{{revision}}'

    - name: output-image
      value: quay.io/redhat-user-workloads/cost-mgmt-dev-tenant/ubi-trino:on-pr-{{revision}}

    - name: image-expires-after
      value: 5d

    - name: dockerfile
      value: Dockerfile

    - name: path-context
      value: .

  pipelineRef:
    name: build-multiarch-pipeline

  taskRunTemplate: {}
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
